### ISSUE TITLE
Would it be hard to use vega instead of vega-lite, when that is necessary?

### ISSUE THREAD

**Issue by JobLeonard** [amitkaps/visdown#1]
Hey, first: this is great stuff, thanks for making it!

Now, vega-lite looks amazing, but at the moment it does not support _interactive_ stuff yet; I know it's planned but I'm a bit impatient. So I was just wondering how hard it would be to replace vega-lite with vega in this build process you outlined on the Google groups message:

> It uses the following three libraries 
> yaml -> json (using yaml.js)
> 
> json -> vega-lite -> svg (using vegalite.js)
> 
> markdown -> html (using marked.js)

My hunch is that it just requires tweaking [this line](https://github.com/amitkaps/visdown/blob/master/visdown.js#L12) but I've only just discovered vega and vega-lite and still have to dig down into the specs and such.

**Comment by amitkaps** [comment]
@JobLeonard Your intuition is correct. You only need to change the `mode: "vega"` and it will take vega spec. Here is a working prototype with the interactive airport vega example - [http://visdown.amitkaps.com/vega.html](http://visdown.amitkaps.com/vega.html). Hope this helps.

**Comment by JobLeonard** [comment]
FYI, I think that adding vega broke the vega-lite demo-site:

![image](https://cloud.githubusercontent.com/assets/259840/18668864/eb5a6d24-7f2f-11e6-921f-57310be1fd30.png)

http://visdown.amitkaps.com/

**Comment by amitkaps** [comment]
Thanks. The css link got deleted!  Fixed it now.

**Comment by JobLeonard** [comment]
BTW, [the Vega 3 branch is open now](https://github.com/uwdata/vega) so you could even have a preview-version of that if you want ;)
